### ISSUE TITLE
Pull request description is limited to 400 characters

### ISSUE THREAD

**Issue by yoelai** [Microsoft/azure-devops-python-api#197]
Hi,

I'm trying to get the description text of a pull request and the text returned is always limited to 400 characters.
The code I am using:

```
pr_search_criteria = GitPullRequestSearchCriteria(status = status)
pull_requests = self._git_client.get_pull_requests(repository_id = self._repo.id, project = self._project.id, search_criteria = pr_search_criteria)
```

The code returns the correct objects, but the description field is limited to 400 chars.

Is this by design? Is there a way of getting around this?

Thanks.

**Comment by bradwillis** [comment]
Hello!

This is an intentional behavior with the bulk Get Pull Request API. If you would like to get the full description of a PR, you can follow up with a request to get the single pull request by Id. That response will contain the full description:
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/get%20pull%20request%20by%20id?view=azure-devops-rest-5.0

Thanks

**Comment by yoelai** [comment]
Thanks, @bradwillis !
