### ISSUE TITLE
Retrieve parents and childs.

### ISSUE THREAD

**Issue by WhatDoesKmean** [microsoft/azure-devops-python-api#238]
Hey!  Thanks for this useful library. I'm able to retrieve a bunch of fields regarding work items (User Stories / Tasks / etc.)
I was wondering if you could post a sample demo on how to retrieve Parent and Child IDs within the work items as well in order to be able to do some correlations. (US id > Task/s id or US id < Task/s id) Thanks again for your help!

**Comment by tedchamb** [comment]
The most straight forward way to do this is probably to create a [WIQL](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops) query, and use the `WorkItemTrackingClient.query_by_wiql` method.

**Comment by tedchamb** [comment]
@WhatDoesKmean , I am going to close this for now.  Let me know if you are still having issues.

**Comment by Brokkolie** [comment]
@tedchamb I also am trying to get the child/parent relations and am using the mentioned method **query_by_wiql**.
I notice that I get correct valus returend in `response = self._send(..` , but apparently the deserialization in 
 `return self._deserialize('[WorkItemUpdate]', self._unwrap_collection(response))` does not work (because it is for workitems and not for relations ?)

Is there any way to get the parent/child relations by now? 

Thanks
