### ISSUE TITLE
How can scheduled deployments be created?

### ISSUE THREAD

**Issue by jarandaf** [microsoft/azure-devops-python-api#275]
I get the following error when trying to specify a scheduled deployment time:

```azure.devops.exceptions.AzureDevOpsServiceError: Invalid input to update stage 'X' of release 'Y'. Make sure you have pending approvals in the stage.```

What does it exactly mean?

**Comment by tedchamb** [comment]
Since this is a question related to the REST API and not specifically about the Python SDK, The best place to submit this question is here:

https://docs.microsoft.com/en-us/rest/api/azure/devops/release/?view=azure-devops-rest-5.1

This way it will get routed to the team that owns this particular REST endpoint.
