### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by dhirschfeld** [microsoft/azure-devops-python-api#306]
What is the story with the `b` in the version numbers? Are all of the releases really *beta* versions?

**Comment by tedchamb** [comment]
Versions 5.1.x have been left as beta (preview) because the fix for #252 will cause a small breaking change.  

Versions 6.0.x will remain beta (preview), until the service releases the 6.0 APIs.  Since the 6.0 APIs on the service are still in preview, when we regenerate clients each sprint there is a chance the new changes can introduce breaking changes.

**Comment by dhirschfeld** [comment]
Thanks for the info!

**Comment by kentyman23** [comment]
@tedchamb Will there be a final version for 7.1? Right now, it's still a beta release.
