### ISSUE TITLE
Any way to use it in TFS2015?

### ISSUE THREAD

**Issue by BBDXF** [microsoft/azure-devops-python-api#317]
How can i use it in TFS2015?
In our service, we need a NTLM Authentication, but i can't find the way.
Please give me some tips or help.

**Comment by Sl1ckR1ck** [comment]
I have the same question. 

If i use the REST API directly i have no problem doing a NTLM authentification:
theResponse = requests.get(url, auth=HttpNtlmAuth(p_UserName, p_UserPassword), data=postData, headers={'Content-Type': 'application/json'})

Since in the end it is using REST, i dont see why it would not be possible?

**Comment by tedchamb** [comment]
It looks like msrest added support for kerberos authentication in Dec 2019, which is what this library uses.  Try using a kerberos credential, and send it to the `Connection` constructor. 

https://github.com/Azure/msrest-for-python/commit/2748e35a5af516930f60d0aebda4159fa752e88e#diff-184af2dedd5eb1126e7a02240db1f214

**Comment by BBDXF** [comment]
@tedchamb Thank you!

**Comment by Sl1ckR1ck** [comment]
@BBDXF, do you have an example on how you've created your connection? I cannot seem to be able to set it up properly. :/ I still get a :
TF400813: Resource not available for anonymous access. Client authentication required.  The requested resource requires user authentication:
