### ISSUE TITLE
Please bump msrest dependency

### ISSUE THREAD

**Issue by glaubitz** [microsoft/azure-devops-python-api#430]
The `msrest` package was recently updated to 0.7.1 while `azure-devops` still has a version ceiling of 0.7.0.

Thus, in order to be compatible with newer installations of the Azure SDK, the package should be ported to `msrest` 0.7.0 or newer.

**Comment by bluenote10** [comment]
What makes this issue even worse is that `azure-devops` has a dependency annotation `msrest<0.7.0`.

Unfortunately this dependency annotation conflicts with many other Azure related Python packages. For instance:

- `azure-mgmt-resource` now has a dependency `msrest>=0.7.1`
- `azure-data-tables` now has a dependency `msrest>=0.7.1`
- `azure-storage-queue` now has a dependency `msrest>=0.7.1`

This means that it is currently impossible to run e.g. `pip-compile` for an environment that wants to mix `azure-devops` with any of these more modern packages, because pip compile will error due to the conflict in the transitive closure of the dependencies.

It would be great if this issue can be addressed with some priority because it causes a dependency hell in the Azure ecosystem in general (down-pinning / holding back lots of other Azure related packages just to satisfy azure-devops).

**Comment by tonybaloney** [comment]
I'm taking a look at this issue now. msrest 0.7.1 requires 3.6+ so this will mean the next version of this package will drop 2.7 support (which was EOL in 2020)

**Comment by harneetvirk** [comment]
@tonybaloney: I see, some recent changes in the setup.py of azure-devops. Do we have any timelines about the new release of azure-devops for 7.0.0?

**Comment by flixman** [comment]
@tonybaloney, as @harneetvirk asked: are there any timelines for zure-devops 7.0? That would be super cool!

**Comment by nechvatalp** [comment]
We released a new version with support for 7.0 and 7.1 APIs, that depends on the msrest 0.7.1 thanks @tonybaloney
