### ISSUE TITLE
No module named 'azure.devops.v7_0.release'

### ISSUE THREAD

**Issue by marcsettin** [microsoft/azure-devops-python-api#454]
Version: 7.1.0b1

Code:
`from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication

personal_access_token = 'TOKEN'

organization_url = 'URL'

credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

client = connection.clients.get_release_client()`

Error: ModuleNotFoundError: No module named 'azure.devops.v7_0.release'

**Comment by cmattmiller** [comment]
Getting the same error.

**Comment by nechvatalp** [comment]
Hi, this should be fixed in the new version 7.1.0b2

This happened because there was .gitignore setup to ignore release folders, there were setup exceptions but they were for specific paths, because I changed the version and with it paths the release files weren't picked up. Updated the .gitignore exception to not be version specific.
